function searchclick() { $.blockUI({ message: '<h3><img src="default_files/url.gif" /><br>...  چند لحظه صبر کنید</h3>' }), tels = $("#txtsearch").val(), subj = $("#subsearch").val(), tydoc = $("#typesearch").val(), $.ajax({ url: "process.aspx?cmd=document&txtsearch=" + tels + "&tydoc=" + tydoc + "&subj=" + subj, type: "GET", success: function (data) { $.unblockUI(), alldata = eval(data), Bind(alldata) }, error: function (n, t, i) { alert(i), $.unblockUI() } }) } function Bind(n) {
    for (len = n.length, _n = "", _n = "نتایج جستجو:  جستجو {k} مورد یافته است. ",
        _n = _n.replace("{k}", n.length), $("#sectionhead").text(_n), _n = "", pagenumber = len / 10, pagenumber = Math.floor(pagenumber), pagenumberceiling = Math.ceil(len / 10), pagenumber != pagenumberceiling && (pagenumber = pagenumberceiling), p = 0; p < pagenumber; p++) _n += "<span id='resultspan{x}'  class='resultspan' onclick=gopage({0}); >{0} </span>", _n = _n.replace("{0}", p + 1), _n = _n.replace("{0}", p + 1), _n = _n.replace("{x}", p + 1); z = _n, $("#Label2").html(z), gopage(1)
}function gopage(n) {    for (n = n - 1, v = alldata.length, kaf = n * 10 + 1, len4 = kaf + 9, _h = "", i = kaf, i = kaf; i <= len4 && i <= v; i++) {
        if (i % 2 == 0)
        { _h += "<tr><th class = 'theeven' colspan='5'>{0}</th><td></td></tr><tr><td>تعداد دریافت {3}  </td><td>تعداد صفحات {1}</td><td>تعداد بازدید {2} </td><td><a href='srcresult.aspx?cmd=search&id={8}'> مشاهده مشخصات </a></td><td><a href='' onclick='delclick(&quot;{7}&quot;,{6});return false;'> <img src='default_files/btnbuysmall.png'/></a></td></tr>"; }
        else
        { _h += "<tr><th class = 'theodd' colspan='5'>{0}</th><td></td></tr><tr><td>تعداد دریافت {3}  </td><td>تعداد صفحات {1}</td><td>تعداد بازدید {2} </td><td><a href='srcresult.aspx?cmd=search&id={8}'> مشاهده مشخصات </a></td><td><a href='' onclick='delclick(&quot;{7}&quot;,{6});return false;'> <img src='default_files/btnbuysmall2.png'/></a></td></tr>"; }
        _h = _h.replace("{0}", alldata[i - 1].name).replace("{1}", alldata[i - 1].countpage).replace("{2}", alldata[i - 1].countview).replace("{3}", alldata[i - 1].countdownload).replace("{7}", "add").replace("{6}", alldata[i - 1].id).replace("{8}", alldata[i - 1].id); $(".resultspan").css("background-color", "#456DB5"), $("#resultspan" + (n + 1)).css("background-color", "black"), $("#cartgrid").html(_h)
    }} var alldata; $(document).ready(function () { }), lwn = 2, len = 1;function delclick(n, t) { $.blockUI({ theme: !0, title: "اضافه/حذف به سبد خرید", message: "<p>به سبد خرید مراجعه کنید..</p>", timeout: 2e3 }), $.ajax({ url: "addtocart.aspx?cmd=" + n + "&productID=" + t, type: "GET", success: function (n) { $.unblockUI(), n == "okdelete" && location.reload(!0), n == "okadd" && $("#erter").css("display", "block") }, error: function (n, t, i) { alert("error"), alert(i), $.unblockUI() } }) };
function initmenu() { var e = document.getElementById("menuV2"), f = e.offsetHeight, t = e.getElementsByTagName("ul"), o = /msie|MSIE 6/.test(navigator.userAgent), i, r, u, n; if (o) for (var s = e.getElementsByTagName("li"), n = 0, h = s.length; n < h; n++) s[n].onmouseover = function () { this.className = "onhover" }, s[n].onmouseout = function () { this.className = "" }; for (n = 0; n < t.length; n++) i = t[n].parentNode, i.getElementsByTagName("a")[0].className += " arrow", t[n].style.right = i.offsetWidth + "px", t[n].style.top = i.offsetTop + "px", alignWithMainMenu && (r = getParentOffsetRoot(i.parentNode, 0), t[n].offsetTop + t[n].offsetHeight + r > f && (u = t[n].offsetHeight > f ? -r : f - t[n].offsetHeight - r, t[n].style.top = u + "px")), i.onmouseover = function () { o && (this.className = "onhover"); var n = this.getElementsByTagName("ul")[0]; n && (n.style.visibility = "visible", n.style.display = "block") }, i.onmouseout = function () { o && (this.className = ""), this.getElementsByTagName("ul")[0].style.visibility = "hidden", this.getElementsByTagName("ul")[0].style.display = "none" }; for (n = t.length - 1; n > -1; n--) t[n].style.display = "none" } function getParentOffsetRoot(n, t) { return n.id == "menuV2" ? t : (t += n.offsetTop, getParentOffsetRoot(n.parentNode.parentNode, t)) } var alignWithMainMenu = !1; window.addEventListener ? window.addEventListener("load", initmenu, !1) : window.attachEvent && window.attachEvent("onload", initmenu);